apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: governance-policy-addon-controller
  name: policy-addon-ctrl-controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: governance-policy-addon-controller
  name: policy-addon-ctrl-leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: governance-policy-addon-controller
  name: policy-addon-ctrl-manager-role
rules:
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - clustermanagementaddons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addon.open-cluster-management.io
  resourceNames:
  - cert-policy-controller
  - config-policy-controller
  - governance-policy-framework
  - iam-policy-controller
  resources:
  - clustermanagementaddons/finalizers
  verbs:
  - update
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - addon.open-cluster-management.io
  resourceNames:
  - cert-policy-controller
  - config-policy-controller
  - governance-policy-framework
  - iam-policy-controller
  resources:
  - managedclusteraddons
  verbs:
  - delete
- apiGroups:
  - addon.open-cluster-management.io
  resourceNames:
  - cert-policy-controller
  - config-policy-controller
  - governance-policy-framework
  - iam-policy-controller
  resources:
  - managedclusteraddons/finalizers
  verbs:
  - update
- apiGroups:
  - addon.open-cluster-management.io
  resourceNames:
  - cert-policy-controller
  - config-policy-controller
  - governance-policy-framework
  - iam-policy-controller
  resources:
  - managedclusteraddons/status
  verbs:
  - patch
  - update
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
  - get
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  verbs:
  - approve
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - cert-policy-controller
  - config-policy-controller
  - governance-policy-framework
  - iam-policy-controller
  resources:
  - leases
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resourceNames:
  - policy-encryption-key
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policies/finalizers
  verbs:
  - update
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - open-cluster-management:cert-policy-controller-hub
  - open-cluster-management:config-policy-controller-hub
  - open-cluster-management:iam-policy-controller-hub
  - open-cluster-management:policy-framework-hub
  resources:
  - clusterroles
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - open-cluster-management:cert-policy-controller-hub
  - open-cluster-management:config-policy-controller-hub
  - open-cluster-management:iam-policy-controller-hub
  - open-cluster-management:policy-framework-hub
  resources:
  - rolebindings
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - work.open-cluster-management.io
  resourceNames:
  - addon-cert-policy-controller-deploy
  - addon-config-policy-controller-deploy
  - addon-governance-policy-framework-deploy
  - addon-iam-policy-controller-deploy
  resources:
  - manifestworks
  verbs:
  - delete
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: governance-policy-addon-controller
  name: policy-addon-ctrl-leader-election-rolebinding
  namespace: hypershift-clusters-acm-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: policy-addon-ctrl-leader-election-role
subjects:
- kind: ServiceAccount
  name: policy-addon-ctrl-controller-manager
  namespace: hypershift-clusters-acm-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: governance-policy-addon-controller
  name: policy-addon-ctrl-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: policy-addon-ctrl-manager-role
subjects:
- kind: ServiceAccount
  name: policy-addon-ctrl-controller-manager
  namespace: hypershift-clusters-acm-1
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: e81fb960.open-cluster-management.io
kind: ConfigMap
metadata:
  labels:
    app: governance-policy-addon-controller
  name: policy-addon-ctrl-manager-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: governance-policy-addon-controller
    control-plane: controller-manager
  name: policy-addon-ctrl-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: governance-policy-addon-controller
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: governance-policy-addon-controller
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - controller
        - --kubeconfig=/var/run/secrets/hypershift/kubeconfig
        command:
        - governance-policy-addon-controller
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CERT_POLICY_CONTROLLER_IMAGE
          value: quay.io/stolostron/cert-policy-controller:latest
        - name: IAM_POLICY_CONTROLLER_IMAGE
          value: quay.io/stolostron/iam-policy-controller:latest
        - name: CONFIG_POLICY_CONTROLLER_IMAGE
          value: quay.io/stolostron/config-policy-controller:latest
        - name: GOVERNANCE_POLICY_SPEC_SYNC_IMAGE
          value: quay.io/stolostron/governance-policy-spec-sync:latest
        - name: GOVERNANCE_POLICY_STATUS_SYNC_IMAGE
          value: quay.io/stolostron/governance-policy-status-sync:latest
        - name: GOVERNANCE_POLICY_TEMPLATE_SYNC_IMAGE
          value: quay.io/stolostron/governance-policy-template-sync:latest
        image: quay.io/stolostron/governance-policy-addon-controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /var/run/secrets/hypershift
          name: kubeconfig
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: service-network-admin-kubeconfig
      securityContext:
        runAsNonRoot: true
      serviceAccountName: policy-addon-ctrl-controller-manager
      terminationGracePeriodSeconds: 10
